
POST http://localhost:3000/customers
Authorization: Bearer 
Content-Type: application/json
{
  "name": "test customer",
  "email": "customer@gmail.com",
  "phone": "09025087789"
}

GET http://localhost:3000/customers
Authorization: Bearer 

GET http://localhost:3000/customers/:id
Authorization: Bearer 

PATCH http://localhost:3000/customers/:id
Authorization: Bearer 
Content-Type: application/json

{
  "phone": "08125087789"
  }

DELETE http://localhost:3000/customers/:id
Authorization: Bearer 