
POST http://localhost:3000/orders
Authorization: Bearer 
Content-Type: application/json
{
  "customerId": 3,
  "measurementId": 3,
  "totalPrice": 12000
}


GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsImVtYWlsIjoiYW1hbGlrYWJkdWxtYWxpa0BnbWFpbC5jb20iLCJyb2xlIjoiVEFJTE9SIiwiaWF0IjoxNzcyOTcyNTU1LCJleHAiOjE3NzI5NzYxNTV9.C4dW53vANg6HbgmXYw7ubfWLnc_1FONcfx-L7PfaZJs



GET http://localhost:3000/orders/1  
Authorization: Bearer 

PATCH http://localhost:3000/orders/1/status
Authorization: Bearer 
Content-Type: application/json
{
  "status": "COMPLETED"
}


DELETE http://localhost:3000/orders/1
Authorization: Bearer 