POST http://localhost:3000/auth/register
Content-Type: application/json
{
  "name": "abdulmalik",
  "email": "amalikabdulmalik@gmail.com",
  "password": "Default$123",
  "role": "TAILOR"
}


POST http://localhost:3000/auth/login
Content-Type: application/json
{
  "email": "ahmadabdulkareem413@gmail.com",
  "password": "Default$123"
}


